export const questions = [
  {
    id: 'q1',
    title: '1. Soru',
    prompt: '"Hola" kelimesinin Turkcesi hangisidir?',
    options: [
      { key: 'A', text: 'Merhaba' },
      { key: 'B', text: 'Tesekkurler' },
      { key: 'C', text: 'Gule gule' },
    ],
    correct: 'A',
  },
  {
    id: 'q2',
    title: '2. Soru',
    prompt: 'Ispanyolcada "tesekkur ederim" nasil soylenir?',
    options: [
      { key: 'A', text: 'Perdon' },
      { key: 'B', text: 'Gracias' },
      { key: 'C', text: 'Adios' },
    ],
    correct: 'B',
  },
  {
    id: 'q3',
    title: '3. Soru',
    prompt: '"Buenos dias" hangi anlama gelir?',
    options: [
      { key: 'A', text: 'Iyi geceler' },
      { key: 'B', text: 'Gorusuruz' },
      { key: 'C', text: 'Gunaydin' },
    ],
    correct: 'C',
  },
  {
    id: 'q4',
    title: '4. Soru',
    prompt: 'Ispanyolcada "iyi geceler" nasil soylenir?',
    options: [
      { key: 'A', text: 'Buenas noches' },
      { key: 'B', text: 'Buenos dias' },
      { key: 'C', text: 'Buenas tardes' },
    ],
    correct: 'A',
  },
  {
    id: 'q5',
    title: '5. Soru',
    prompt: '"Adios" kelimesinin Turkcesi hangisidir?',
    options: [
      { key: 'A', text: 'Lutfen' },
      { key: 'B', text: 'Gule gule' },
      { key: 'C', text: 'Evet' },
    ],
    correct: 'B',
  },
  {
    id: 'q6',
    title: '6. Soru',
    prompt: 'Ispanyolcada "lutfen" nasil soylenir?',
    options: [
      { key: 'A', text: 'De nada' },
      { key: 'B', text: 'Hola' },
      { key: 'C', text: 'Por favor' },
    ],
    correct: 'C',
  },
  {
    id: 'q7',
    title: '7. Soru',
    prompt: '"De nada" ifadesi ne demektir?',
    options: [
      { key: 'A', text: 'Rica ederim' },
      { key: 'B', text: 'Gunaydin' },
      { key: 'C', text: 'Neredesin' },
    ],
    correct: 'A',
  },
  {
    id: 'q8',
    title: '8. Soru',
    prompt: 'Ispanyolcada "evet" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'No' },
      { key: 'B', text: 'Si' },
      { key: 'C', text: 'Tal vez' },
    ],
    correct: 'B',
  },
  {
    id: 'q9',
    title: '9. Soru',
    prompt: 'Ispanyolcada "hayir" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Si' },
      { key: 'B', text: 'Vale' },
      { key: 'C', text: 'No' },
    ],
    correct: 'C',
  },
  {
    id: 'q10',
    title: '10. Soru',
    prompt: '"Como estas?" sorusu ne anlama gelir?',
    options: [
      { key: 'A', text: 'Nasilsin?' },
      { key: 'B', text: 'Saat kac?' },
      { key: 'C', text: 'Nerelisin?' },
    ],
    correct: 'A',
  },
  {
    id: 'q11',
    title: '11. Soru',
    prompt: 'Ispanyolcada "ben" zamiri hangisidir?',
    options: [
      { key: 'A', text: 'Tu' },
      { key: 'B', text: 'Yo' },
      { key: 'C', text: 'Ella' },
    ],
    correct: 'B',
  },
  {
    id: 'q12',
    title: '12. Soru',
    prompt: 'Ispanyolcada "sen" zamiri hangisidir?',
    options: [
      { key: 'A', text: 'El' },
      { key: 'B', text: 'Nosotros' },
      { key: 'C', text: 'Tu' },
    ],
    correct: 'C',
  },
  {
    id: 'q13',
    title: '13. Soru',
    prompt: 'Ispanyolcada eril tekil belirli artikel hangisidir?',
    options: [
      { key: 'A', text: 'El' },
      { key: 'B', text: 'La' },
      { key: 'C', text: 'Las' },
    ],
    correct: 'A',
  },
  {
    id: 'q14',
    title: '14. Soru',
    prompt: 'Ispanyolcada disil tekil belirli artikel hangisidir?',
    options: [
      { key: 'A', text: 'Los' },
      { key: 'B', text: 'La' },
      { key: 'C', text: 'El' },
    ],
    correct: 'B',
  },
  {
    id: 'q15',
    title: '15. Soru',
    prompt: '"La casa" ifadesinde "casa" ne demektir?',
    options: [
      { key: 'A', text: 'Araba' },
      { key: 'B', text: 'Okul' },
      { key: 'C', text: 'Ev' },
    ],
    correct: 'C',
  },
  {
    id: 'q16',
    title: '16. Soru',
    prompt: '"El libro" ifadesinde "libro" ne demektir?',
    options: [
      { key: 'A', text: 'Kitap' },
      { key: 'B', text: 'Defter' },
      { key: 'C', text: 'Kalem' },
    ],
    correct: 'A',
  },
  {
    id: 'q17',
    title: '17. Soru',
    prompt: 'Ispanyolcada "su" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Pan' },
      { key: 'B', text: 'Agua' },
      { key: 'C', text: 'Leche' },
    ],
    correct: 'B',
  },
  {
    id: 'q18',
    title: '18. Soru',
    prompt: 'Ispanyolcada "ekmek" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Queso' },
      { key: 'B', text: 'Carne' },
      { key: 'C', text: 'Pan' },
    ],
    correct: 'C',
  },
  {
    id: 'q19',
    title: '19. Soru',
    prompt: 'Ispanyolcada "okul" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Escuela' },
      { key: 'B', text: 'Calle' },
      { key: 'C', text: 'Mesa' },
    ],
    correct: 'A',
  },
  {
    id: 'q20',
    title: '20. Soru',
    prompt: '"Mesa" kelimesinin Turkcesi nedir?',
    options: [
      { key: 'A', text: 'Sandalye' },
      { key: 'B', text: 'Masa' },
      { key: 'C', text: 'Kapi' },
    ],
    correct: 'B',
  },
  {
    id: 'q21',
    title: '21. Soru',
    prompt: '"Silla" kelimesinin Turkcesi nedir?',
    options: [
      { key: 'A', text: 'Pencere' },
      { key: 'B', text: 'Dolap' },
      { key: 'C', text: 'Sandalye' },
    ],
    correct: 'C',
  },
  {
    id: 'q22',
    title: '22. Soru',
    prompt: 'Ispanyolcada "kirmizi" rengi hangisidir?',
    options: [
      { key: 'A', text: 'Rojo' },
      { key: 'B', text: 'Verde' },
      { key: 'C', text: 'Azul' },
    ],
    correct: 'A',
  },
  {
    id: 'q23',
    title: '23. Soru',
    prompt: 'Ispanyolcada "mavi" rengi hangisidir?',
    options: [
      { key: 'A', text: 'Negro' },
      { key: 'B', text: 'Azul' },
      { key: 'C', text: 'Blanco' },
    ],
    correct: 'B',
  },
  {
    id: 'q24',
    title: '24. Soru',
    prompt: 'Ispanyolcada "yesil" rengi hangisidir?',
    options: [
      { key: 'A', text: 'Amarillo' },
      { key: 'B', text: 'Rojo' },
      { key: 'C', text: 'Verde' },
    ],
    correct: 'C',
  },
  {
    id: 'q25',
    title: '25. Soru',
    prompt: 'Ispanyolcada "bir" sayisi hangisidir?',
    options: [
      { key: 'A', text: 'Uno' },
      { key: 'B', text: 'Dos' },
      { key: 'C', text: 'Tres' },
    ],
    correct: 'A',
  },
  {
    id: 'q26',
    title: '26. Soru',
    prompt: 'Ispanyolcada "iki" sayisi hangisidir?',
    options: [
      { key: 'A', text: 'Uno' },
      { key: 'B', text: 'Dos' },
      { key: 'C', text: 'Cuatro' },
    ],
    correct: 'B',
  },
  {
    id: 'q27',
    title: '27. Soru',
    prompt: 'Ispanyolcada "uc" sayisi hangisidir?',
    options: [
      { key: 'A', text: 'Cinco' },
      { key: 'B', text: 'Dos' },
      { key: 'C', text: 'Tres' },
    ],
    correct: 'C',
  },
  {
    id: 'q28',
    title: '28. Soru',
    prompt: 'Ispanyolcada "dort" sayisi hangisidir?',
    options: [
      { key: 'A', text: 'Cuatro' },
      { key: 'B', text: 'Siete' },
      { key: 'C', text: 'Ocho' },
    ],
    correct: 'A',
  },
  {
    id: 'q29',
    title: '29. Soru',
    prompt: 'Ispanyolcada "bes" sayisi hangisidir?',
    options: [
      { key: 'A', text: 'Nueve' },
      { key: 'B', text: 'Cinco' },
      { key: 'C', text: 'Diez' },
    ],
    correct: 'B',
  },
  {
    id: 'q30',
    title: '30. Soru',
    prompt: 'Ispanyolcada "on" sayisi hangisidir?',
    options: [
      { key: 'A', text: 'Seis' },
      { key: 'B', text: 'Siete' },
      { key: 'C', text: 'Diez' },
    ],
    correct: 'C',
  },
  {
    id: 'q31',
    title: '31. Soru',
    prompt: 'Ispanyolcada "benim adim..." nasil baslar?',
    options: [
      { key: 'A', text: 'Me llamo...' },
      { key: 'B', text: 'Tengo...' },
      { key: 'C', text: 'Estoy...' },
    ],
    correct: 'A',
  },
  {
    id: 'q32',
    title: '32. Soru',
    prompt: '"Tengo hambre" ne demektir?',
    options: [
      { key: 'A', text: 'Susadim' },
      { key: 'B', text: 'Aciktim' },
      { key: 'C', text: 'Yorgunum' },
    ],
    correct: 'B',
  },
  {
    id: 'q33',
    title: '33. Soru',
    prompt: '"Tengo sed" ne demektir?',
    options: [
      { key: 'A', text: 'Uykum var' },
      { key: 'B', text: 'Aciktim' },
      { key: 'C', text: 'Susadim' },
    ],
    correct: 'C',
  },
  {
    id: 'q34',
    title: '34. Soru',
    prompt: 'Ispanyolcada "nerede?" sorusu hangisidir?',
    options: [
      { key: 'A', text: 'Donde?' },
      { key: 'B', text: 'Cuando?' },
      { key: 'C', text: 'Quien?' },
    ],
    correct: 'A',
  },
  {
    id: 'q35',
    title: '35. Soru',
    prompt: 'Ispanyolcada "ne zaman?" sorusu hangisidir?',
    options: [
      { key: 'A', text: 'Que?' },
      { key: 'B', text: 'Cuando?' },
      { key: 'C', text: 'Como?' },
    ],
    correct: 'B',
  },
  {
    id: 'q36',
    title: '36. Soru',
    prompt: 'Ispanyolcada "kim?" sorusu hangisidir?',
    options: [
      { key: 'A', text: 'Donde?' },
      { key: 'B', text: 'Cuanto?' },
      { key: 'C', text: 'Quien?' },
    ],
    correct: 'C',
  },
  {
    id: 'q37',
    title: '37. Soru',
    prompt: 'Ispanyolcada "ne?" sorusu hangisidir?',
    options: [
      { key: 'A', text: 'Que?' },
      { key: 'B', text: 'Quien?' },
      { key: 'C', text: 'Cuando?' },
    ],
    correct: 'A',
  },
  {
    id: 'q38',
    title: '38. Soru',
    prompt: 'Ispanyolcada "nasil?" sorusu hangisidir?',
    options: [
      { key: 'A', text: 'Cuanto?' },
      { key: 'B', text: 'Como?' },
      { key: 'C', text: 'Donde?' },
    ],
    correct: 'B',
  },
  {
    id: 'q39',
    title: '39. Soru',
    prompt: 'Ispanyolcada "neden?" sorusu hangisidir?',
    options: [
      { key: 'A', text: 'Para que?' },
      { key: 'B', text: 'Como?' },
      { key: 'C', text: 'Por que?' },
    ],
    correct: 'C',
  },
  {
    id: 'q40',
    title: '40. Soru',
    prompt: '"Soy estudiante" ne demektir?',
    options: [
      { key: 'A', text: 'Ogrenciyim' },
      { key: 'B', text: 'Ogretmenim' },
      { key: 'C', text: 'Doktorum' },
    ],
    correct: 'A',
  },
  {
    id: 'q41',
    title: '41. Soru',
    prompt: '"Soy de Turquia" ne demektir?',
    options: [
      { key: 'A', text: 'Turkce konusuyorum' },
      { key: 'B', text: 'Turkiyeliyim' },
      { key: 'C', text: 'Turkiye guzeldir' },
    ],
    correct: 'B',
  },
  {
    id: 'q42',
    title: '42. Soru',
    prompt: '"Estoy cansado" ne demektir?',
    options: [
      { key: 'A', text: 'Mutluyum' },
      { key: 'B', text: 'Hastayim' },
      { key: 'C', text: 'Yorgunum' },
    ],
    correct: 'C',
  },
  {
    id: 'q43',
    title: '43. Soru',
    prompt: 'Kalici kimlik/meslek icin genelde hangi fiil kullanilir?',
    options: [
      { key: 'A', text: 'Ser' },
      { key: 'B', text: 'Estar' },
      { key: 'C', text: 'Tener' },
    ],
    correct: 'A',
  },
  {
    id: 'q44',
    title: '44. Soru',
    prompt: 'Gecici durum veya konum icin genelde hangi fiil kullanilir?',
    options: [
      { key: 'A', text: 'Ser' },
      { key: 'B', text: 'Estar' },
      { key: 'C', text: 'Hacer' },
    ],
    correct: 'B',
  },
  {
    id: 'q45',
    title: '45. Soru',
    prompt: '"Tengo veinte anos" ne demektir?',
    options: [
      { key: 'A', text: 'Yirmi gunum var' },
      { key: 'B', text: 'Yirmi kitabim var' },
      { key: 'C', text: 'Yirmi yasindayim' },
    ],
    correct: 'C',
  },
  {
    id: 'q46',
    title: '46. Soru',
    prompt: 'Ispanyolcada "ve" baglaci hangisidir?',
    options: [
      { key: 'A', text: 'Y' },
      { key: 'B', text: 'O' },
      { key: 'C', text: 'Pero' },
    ],
    correct: 'A',
  },
  {
    id: 'q47',
    title: '47. Soru',
    prompt: 'Ispanyolcada "veya" baglaci hangisidir?',
    options: [
      { key: 'A', text: 'Y' },
      { key: 'B', text: 'O' },
      { key: 'C', text: 'Porque' },
    ],
    correct: 'B',
  },
  {
    id: 'q48',
    title: '48. Soru',
    prompt: 'Ispanyolcada "ama/fakat" baglaci hangisidir?',
    options: [
      { key: 'A', text: 'Porque' },
      { key: 'B', text: 'Tambien' },
      { key: 'C', text: 'Pero' },
    ],
    correct: 'C',
  },
  {
    id: 'q49',
    title: '49. Soru',
    prompt: 'Ispanyolcada "bugun" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Hoy' },
      { key: 'B', text: 'Manana' },
      { key: 'C', text: 'Ayer' },
    ],
    correct: 'A',
  },
  {
    id: 'q50',
    title: '50. Soru',
    prompt: 'Ispanyolcada "yarin" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Ayer' },
      { key: 'B', text: 'Manana' },
      { key: 'C', text: 'Hoy' },
    ],
    correct: 'B',
  },
  {
    id: 'q51',
    title: '51. Soru',
    prompt: 'Ispanyolcada "dun" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Hoy' },
      { key: 'B', text: 'Ahora' },
      { key: 'C', text: 'Ayer' },
    ],
    correct: 'C',
  },
  {
    id: 'q52',
    title: '52. Soru',
    prompt: 'Ispanyolcada "simdi" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Ahora' },
      { key: 'B', text: 'Luego' },
      { key: 'C', text: 'Nunca' },
    ],
    correct: 'A',
  },
  {
    id: 'q53',
    title: '53. Soru',
    prompt: 'Ispanyolcada "her zaman" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Nunca' },
      { key: 'B', text: 'Siempre' },
      { key: 'C', text: 'A veces' },
    ],
    correct: 'B',
  },
  {
    id: 'q54',
    title: '54. Soru',
    prompt: 'Ispanyolcada "asla" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Siempre' },
      { key: 'B', text: 'Tambien' },
      { key: 'C', text: 'Nunca' },
    ],
    correct: 'C',
  },
  {
    id: 'q55',
    title: '55. Soru',
    prompt: '"Me gusta el cafe" ne demektir?',
    options: [
      { key: 'A', text: 'Kahveyi severim' },
      { key: 'B', text: 'Kahve istemem' },
      { key: 'C', text: 'Kahve soguk' },
    ],
    correct: 'A',
  },
  {
    id: 'q56',
    title: '56. Soru',
    prompt: '"No me gusta" ne demektir?',
    options: [
      { key: 'A', text: 'Severim' },
      { key: 'B', text: 'Sevmem' },
      { key: 'C', text: 'Bilmiyorum' },
    ],
    correct: 'B',
  },
  {
    id: 'q57',
    title: '57. Soru',
    prompt: 'Ispanyolcada "konusmak" fiili hangisidir?',
    options: [
      { key: 'A', text: 'Comer' },
      { key: 'B', text: 'Vivir' },
      { key: 'C', text: 'Hablar' },
    ],
    correct: 'C',
  },
  {
    id: 'q58',
    title: '58. Soru',
    prompt: 'Ispanyolcada "yemek yemek" fiili hangisidir?',
    options: [
      { key: 'A', text: 'Comer' },
      { key: 'B', text: 'Beber' },
      { key: 'C', text: 'Leer' },
    ],
    correct: 'A',
  },
  {
    id: 'q59',
    title: '59. Soru',
    prompt: 'Ispanyolcada "yasamak" fiili hangisidir?',
    options: [
      { key: 'A', text: 'Abrir' },
      { key: 'B', text: 'Vivir' },
      { key: 'C', text: 'Correr' },
    ],
    correct: 'B',
  },
  {
    id: 'q60',
    title: '60. Soru',
    prompt: 'Ispanyolcada "okumak" fiili hangisidir?',
    options: [
      { key: 'A', text: 'Escribir' },
      { key: 'B', text: 'Escuchar' },
      { key: 'C', text: 'Leer' },
    ],
    correct: 'C',
  },
  {
    id: 'q61',
    title: '61. Soru',
    prompt: 'Ispanyolcada "yazmak" fiili hangisidir?',
    options: [
      { key: 'A', text: 'Escribir' },
      { key: 'B', text: 'Mirar' },
      { key: 'C', text: 'Comprar' },
    ],
    correct: 'A',
  },
  {
    id: 'q62',
    title: '62. Soru',
    prompt: 'Ispanyolcada "dinlemek" fiili hangisidir?',
    options: [
      { key: 'A', text: 'Leer' },
      { key: 'B', text: 'Escuchar' },
      { key: 'C', text: 'Abrir' },
    ],
    correct: 'B',
  },
  {
    id: 'q63',
    title: '63. Soru',
    prompt: 'Ispanyolcada "bakmak/izlemek" fiili hangisidir?',
    options: [
      { key: 'A', text: 'Beber' },
      { key: 'B', text: 'Cantar' },
      { key: 'C', text: 'Mirar' },
    ],
    correct: 'C',
  },
  {
    id: 'q64',
    title: '64. Soru',
    prompt: '"Yo hablo espanol" ne demektir?',
    options: [
      { key: 'A', text: 'Ben Ispanyolca konusurum' },
      { key: 'B', text: 'Sen Ispanyolca konusursun' },
      { key: 'C', text: 'O Ispanyolca konusur' },
    ],
    correct: 'A',
  },
  {
    id: 'q65',
    title: '65. Soru',
    prompt: '"Tu comes pan" ne demektir?',
    options: [
      { key: 'A', text: 'Ben ekmek yerim' },
      { key: 'B', text: 'Sen ekmek yersin' },
      { key: 'C', text: 'Onlar ekmek yer' },
    ],
    correct: 'B',
  },
  {
    id: 'q66',
    title: '66. Soru',
    prompt: '"Ella vive en Madrid" ne demektir?',
    options: [
      { key: 'A', text: 'Ben Madridde yasarim' },
      { key: 'B', text: 'Sen Madridde yasarsin' },
      { key: 'C', text: 'O Madridde yasar' },
    ],
    correct: 'C',
  },
  {
    id: 'q67',
    title: '67. Soru',
    prompt: 'Ispanyolcada "anne" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Madre' },
      { key: 'B', text: 'Padre' },
      { key: 'C', text: 'Hermano' },
    ],
    correct: 'A',
  },
  {
    id: 'q68',
    title: '68. Soru',
    prompt: 'Ispanyolcada "baba" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Madre' },
      { key: 'B', text: 'Padre' },
      { key: 'C', text: 'Hermana' },
    ],
    correct: 'B',
  },
  {
    id: 'q69',
    title: '69. Soru',
    prompt: 'Ispanyolcada "erkek kardes" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Hija' },
      { key: 'B', text: 'Padre' },
      { key: 'C', text: 'Hermano' },
    ],
    correct: 'C',
  },
  {
    id: 'q70',
    title: '70. Soru',
    prompt: 'Ispanyolcada "kiz kardes" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Hermana' },
      { key: 'B', text: 'Hijo' },
      { key: 'C', text: 'Abuelo' },
    ],
    correct: 'A',
  },
  {
    id: 'q71',
    title: '71. Soru',
    prompt: 'Ispanyolcada "arkadas" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Profesor' },
      { key: 'B', text: 'Amigo' },
      { key: 'C', text: 'Alumno' },
    ],
    correct: 'B',
  },
  {
    id: 'q72',
    title: '72. Soru',
    prompt: 'Ispanyolcada "ogretmen" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Amigo' },
      { key: 'B', text: 'Medico' },
      { key: 'C', text: 'Profesor' },
    ],
    correct: 'C',
  },
  {
    id: 'q73',
    title: '73. Soru',
    prompt: 'Ispanyolcada "sehir" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Ciudad' },
      { key: 'B', text: 'Pais' },
      { key: 'C', text: 'Calle' },
    ],
    correct: 'A',
  },
  {
    id: 'q74',
    title: '74. Soru',
    prompt: 'Ispanyolcada "ulke" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Ciudad' },
      { key: 'B', text: 'Pais' },
      { key: 'C', text: 'Pueblo' },
    ],
    correct: 'B',
  },
  {
    id: 'q75',
    title: '75. Soru',
    prompt: 'Ispanyolcada "sokak" kelimesi hangisidir?',
    options: [
      { key: 'A', text: 'Casa' },
      { key: 'B', text: 'Plaza' },
      { key: 'C', text: 'Calle' },
    ],
    correct: 'C',
  },
  {
    id: 'q76',
    title: '76. Soru',
    prompt: '"Me llamo Ana" ne demektir?',
    options: [
      { key: 'A', text: 'Benim adim Ana' },
      { key: 'B', text: 'Ana buradadir' },
      { key: 'C', text: 'Ana konusuyor' },
    ],
    correct: 'A',
  },
  {
    id: 'q77',
    title: '77. Soru',
    prompt: '"Cuantos anos tienes?" ne demektir?',
    options: [
      { key: 'A', text: 'Nerede yasiyorsun?' },
      { key: 'B', text: 'Kac yasindasin?' },
      { key: 'C', text: 'Adin ne?' },
    ],
    correct: 'B',
  },
  {
    id: 'q78',
    title: '78. Soru',
    prompt: '"Donde vives?" ne demektir?',
    options: [
      { key: 'A', text: 'Ne yiyorsun?' },
      { key: 'B', text: 'Ne zaman gidiyorsun?' },
      { key: 'C', text: 'Nerede yasiyorsun?' },
    ],
    correct: 'C',
  },
  {
    id: 'q79',
    title: '79. Soru',
    prompt: 'Ispanyolcada "cok iyi" ifadesi hangisidir?',
    options: [
      { key: 'A', text: 'Muy bien' },
      { key: 'B', text: 'Muy mal' },
      { key: 'C', text: 'Mas o menos' },
    ],
    correct: 'A',
  },
  {
    id: 'q80',
    title: '80. Soru',
    prompt: '"Mas o menos" ne demektir?',
    options: [
      { key: 'A', text: 'Cok iyi' },
      { key: 'B', text: 'Soyle boyle' },
      { key: 'C', text: 'Cok kotu' },
    ],
    correct: 'B',
  },
  {
    id: 'q81',
    title: '81. Soru',
    prompt: 'Ispanyolcada "pazartesi" hangisidir?',
    options: [
      { key: 'A', text: 'Martes' },
      { key: 'B', text: 'Viernes' },
      { key: 'C', text: 'Lunes' },
    ],
    correct: 'C',
  },
  {
    id: 'q82',
    title: '82. Soru',
    prompt: 'Ispanyolcada "sali" hangisidir?',
    options: [
      { key: 'A', text: 'Martes' },
      { key: 'B', text: 'Lunes' },
      { key: 'C', text: 'Domingo' },
    ],
    correct: 'A',
  },
  {
    id: 'q83',
    title: '83. Soru',
    prompt: 'Ispanyolcada "cuma" hangisidir?',
    options: [
      { key: 'A', text: 'Jueves' },
      { key: 'B', text: 'Viernes' },
      { key: 'C', text: 'Sabado' },
    ],
    correct: 'B',
  },
  {
    id: 'q84',
    title: '84. Soru',
    prompt: 'Ispanyolcada "pazar" hangisidir?',
    options: [
      { key: 'A', text: 'Sabado' },
      { key: 'B', text: 'Miercoles' },
      { key: 'C', text: 'Domingo' },
    ],
    correct: 'C',
  },
  {
    id: 'q85',
    title: '85. Soru',
    prompt: 'Ispanyolcada "ocak" ayi hangisidir?',
    options: [
      { key: 'A', text: 'Enero' },
      { key: 'B', text: 'Marzo' },
      { key: 'C', text: 'Julio' },
    ],
    correct: 'A',
  },
  {
    id: 'q86',
    title: '86. Soru',
    prompt: 'Ispanyolcada "mayis" ayi hangisidir?',
    options: [
      { key: 'A', text: 'Abril' },
      { key: 'B', text: 'Mayo' },
      { key: 'C', text: 'Junio' },
    ],
    correct: 'B',
  },
  {
    id: 'q87',
    title: '87. Soru',
    prompt: 'Ispanyolcada "aralik" ayi hangisidir?',
    options: [
      { key: 'A', text: 'Noviembre' },
      { key: 'B', text: 'Enero' },
      { key: 'C', text: 'Diciembre' },
    ],
    correct: 'C',
  },
  {
    id: 'q88',
    title: '88. Soru',
    prompt: 'Ispanyolcada "saat kac?" nasil sorulur?',
    options: [
      { key: 'A', text: 'Que hora es?' },
      { key: 'B', text: 'Como te llamas?' },
      { key: 'C', text: 'Donde esta?' },
    ],
    correct: 'A',
  },
  {
    id: 'q89',
    title: '89. Soru',
    prompt: '"Es la una" hangi saat ifadesidir?',
    options: [
      { key: 'A', text: 'Saat iki' },
      { key: 'B', text: 'Saat bir' },
      { key: 'C', text: 'Saat uc' },
    ],
    correct: 'B',
  },
  {
    id: 'q90',
    title: '90. Soru',
    prompt: '"Son las dos" hangi saat ifadesidir?',
    options: [
      { key: 'A', text: 'Saat bir' },
      { key: 'B', text: 'Saat on' },
      { key: 'C', text: 'Saat iki' },
    ],
    correct: 'C',
  },
  {
    id: 'q91',
    title: '91. Soru',
    prompt: 'Ispanyolcada "sol" yonu hangisidir?',
    options: [
      { key: 'A', text: 'Izquierda' },
      { key: 'B', text: 'Derecha' },
      { key: 'C', text: 'Recto' },
    ],
    correct: 'A',
  },
  {
    id: 'q92',
    title: '92. Soru',
    prompt: 'Ispanyolcada "sag" yonu hangisidir?',
    options: [
      { key: 'A', text: 'Izquierda' },
      { key: 'B', text: 'Derecha' },
      { key: 'C', text: 'Atras' },
    ],
    correct: 'B',
  },
  {
    id: 'q93',
    title: '93. Soru',
    prompt: 'Ispanyolcada "duz ileri" ifadesi hangisidir?',
    options: [
      { key: 'A', text: 'A la derecha' },
      { key: 'B', text: 'A la izquierda' },
      { key: 'C', text: 'Todo recto' },
    ],
    correct: 'C',
  },
  {
    id: 'q94',
    title: '94. Soru',
    prompt: '"Quiero agua" ne demektir?',
    options: [
      { key: 'A', text: 'Su istiyorum' },
      { key: 'B', text: 'Su iciyorum' },
      { key: 'C', text: 'Su yok' },
    ],
    correct: 'A',
  },
  {
    id: 'q95',
    title: '95. Soru',
    prompt: '"Necesito ayuda" ne demektir?',
    options: [
      { key: 'A', text: 'Yardim ederim' },
      { key: 'B', text: 'Yardima ihtiyacim var' },
      { key: 'C', text: 'Yardim istemem' },
    ],
    correct: 'B',
  },
  {
    id: 'q96',
    title: '96. Soru',
    prompt: '"No entiendo" ne demektir?',
    options: [
      { key: 'A', text: 'Anladim' },
      { key: 'B', text: 'Duyamiyorum' },
      { key: 'C', text: 'Anlamiyorum' },
    ],
    correct: 'C',
  },
  {
    id: 'q97',
    title: '97. Soru',
    prompt: '"Hablas ingles?" ne demektir?',
    options: [
      { key: 'A', text: 'Ingilizce konusuyor musun?' },
      { key: 'B', text: 'Ispanyolca konusuyor musun?' },
      { key: 'C', text: 'Ingiliz misin?' },
    ],
    correct: 'A',
  },
  {
    id: 'q98',
    title: '98. Soru',
    prompt: '"Hasta luego" ne demektir?',
    options: [
      { key: 'A', text: 'Hemen gel' },
      { key: 'B', text: 'Sonra gorusuruz' },
      { key: 'C', text: 'Iyi geceler' },
    ],
    correct: 'B',
  },
  {
    id: 'q99',
    title: '99. Soru',
    prompt: '"Perdon" kelimesi hangi anlamda kullanilir?',
    options: [
      { key: 'A', text: 'Tesekkur' },
      { key: 'B', text: 'Gunaydin' },
      { key: 'C', text: 'Afedersiniz' },
    ],
    correct: 'C',
  },
  {
    id: 'q100',
    title: '100. Soru',
    prompt: '"Vale" ifadesi gunluk dilde ne demektir?',
    options: [
      { key: 'A', text: 'Tamam' },
      { key: 'B', text: 'Hayir' },
      { key: 'C', text: 'Lutfen' },
    ],
    correct: 'A',
  },
];

export function createQuestionOrder() {
  const lockQuestions = questions.slice(0, 3);
  const remainingQuestions = [...questions.slice(3)];

  for (let index = remainingQuestions.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [remainingQuestions[index], remainingQuestions[swapIndex]] = [
      remainingQuestions[swapIndex],
      remainingQuestions[index],
    ];
  }

  return [...lockQuestions, ...remainingQuestions];
}
